name: Docker Build

on:
  push:
    branches:
      - develop
      - release/**
      - brapi-server-v2
      
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})
        id: extract_branch
        
      - run: git pull origin ${{steps.extract_branch.outputs.branch}}
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn clean install
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set tag
        id: vars
        run: echo ::set-output name=imageName::$(echo breedinginsight/brapi-java-server:${{ github.run_number }}))
      - name: Build Docker and push image
        run: |
          docker build . --file Dockerfile --tag ${{steps.vars.outputs.imageName}}
          docker push ${{steps.vars.outputs.imageName}}
      - name: Tag develop
        if: steps.extract_branch.outputs.branch == 'develop'
        run: |
          docker tag ${{steps.vars.outputs.imageName}} breedinginsight/biapi:develop
          docker push breedinginsight/biapi:develop
      - name: Tag release candidate
        if: contains(github.ref, '/release/')
        run: |
          docker tag ${{steps.vars.outputs.imageName}} breedinginsight/biapi:rc
          docker push breedinginsight/biapi:rc
      - name: Tag latest
        if: steps.extract_branch.outputs.branch == 'brapi-server-v2'
        run: |
          docker tag ${{steps.vars.outputs.imageName}} breedinginsight/biapi:latest
          docker push breedinginsight/biapi:latest
