name: Docker Build

on:
  push:
    branches:
      - develop
      - release/**
      - brapi-server-v2
      
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})
        id: extract_branch
        
      - run: git pull origin ${{steps.extract_branch.outputs.branch}}
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm,amd64,amd'        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set tag
        id: vars
        run: echo ::set-output name=imageName::$(echo breedinginsight/brapi-java-server:${{ github.run_number }})
        
      - name: Tag develop
        if: steps.extract_branch.outputs.branch == 'develop'
        run: echo ::set-output name=streamName::$(echo breedinginsight/brapi-java-server:develop)
      - name: Tag release candidate
        if: contains(github.ref, '/release/')
        run: echo ::set-output name=streamName::$(echo breedinginsight/brapi-java-server:rc)
      - name: Tag latest
        if: steps.extract_branch.outputs.branch == 'brapi-server-v2'
        run: echo ::set-output name=streamName::$(echo breedinginsight/brapi-java-server:latest)
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: |-
              linux/amd64
              linux/arm64
          push: true
          tags: '${{steps.vars.outputs.imageName}},${{steps.vars.outputs.streamName}}'

#       - name: Build Docker and push image
#         run: |
#           docker build . --file Dockerfile --tag ${{steps.vars.outputs.imageName}}
#           docker push ${{steps.vars.outputs.imageName}}

#       - name: Tag develop
#         if: steps.extract_branch.outputs.branch == 'develop'
#         run: |
#           docker tag ${{steps.vars.outputs.imageName}} breedinginsight/brapi-java-server:develop
#           docker push breedinginsight/brapi-java-server:develop
#       - name: Tag release candidate
#         if: contains(github.ref, '/release/')
#         run: |
#           docker tag ${{steps.vars.outputs.imageName}} breedinginsight/brapi-java-server:rc
#           docker push breedinginsight/brapi-java-server:rc
#       - name: Tag latest
#         if: steps.extract_branch.outputs.branch == 'brapi-server-v2'
#         run: |
#           docker tag ${{steps.vars.outputs.imageName}} breedinginsight/brapi-java-server:latest
#           docker push breedinginsight/brapi-java-server:latest
